# Generated by Django 6.0.6 on 2026-07-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Blog', max_length=200, verbose_name='网站标题')),
                ('site_description', models.TextField(blank=True, default='', verbose_name='网站描述')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='网站Logo')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='网站图标')),
                ('blog_background', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='博客背景图')),
                ('about_content', models.TextField(blank=True, default='', verbose_name='关于页面内容')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='社交账号链接')),
                ('welcome_messages', models.JSONField(blank=True, default=list, verbose_name='随机问候语列表')),
                ('splash_animation_text', models.CharField(blank=True, default='', max_length=200, verbose_name='开屏动画文字')),
                ('splash_animation_bg', models.CharField(blank=True, default='#1a1a2e', max_length=50, verbose_name='开屏动画背景色')),
                ('splash_animation_theme', models.CharField(blank=True, default='default', max_length=50, verbose_name='开屏动画主题')),
                ('articles_per_page', models.IntegerField(default=10, verbose_name='每页文章数')),
                ('show_article_stats', models.BooleanField(default=True, verbose_name='展示文章统计信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('slug', models.SlugField(unique=True, verbose_name='标签标识')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='分类标识')),
                ('description', models.TextField(blank=True, default='', verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='文章标识')),
                ('content', models.TextField(verbose_name='正文内容(Markdown)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='文章摘要')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='封面图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('article_type', models.CharField(choices=[('article', '文章'), ('diary', '日记'), ('about', '关于')], default='article', max_length=20, verbose_name='文章类型')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200, verbose_name='SEO标题')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO描述')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='文章')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=200, verbose_name='菜单链接/路由')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='菜单图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.menuitem', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
                'ordering': ['order', 'name'],
            },
        ),
    ]
