# Generated by Django 6.0.6 on 2026-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ensure_default_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='菜单链接/路由'),
        ),
    ]
